In [1]:
import pandas as pd

In [2]:
ress={}
ress_rand={}
nun_seed=10
for seed in range(1,nun_seed):
    ress[seed] = pd.read_csv(f"./data/eq_05_data_deltas_2_gamma_n_326_d_10_tlim_12_lam_0.5_mu_1e-10_s_{seed}_pe_1_0_trace.gz")    
    ress_rand[seed] = pd.read_csv(f"./data/eq_05_rand_data_deltas_2_gamma_n_326_d_10_tlim_12_lam_0.5_mu_1e-10_s_{seed}_pe_1_0_trace.gz")

In [3]:
import numpy as np
gammas1=[]
gammas2=[]
gammas1_rand=[]
gammas2_rand=[]
betas = []
betas_rand = []
for seed in range(1,nun_seed):
    gammas1.append(ress[seed]["gamma1"][-100:].mean())
    gammas2.append(ress[seed]["gamma2"][-100:].mean())
    gammas1_rand.append(ress_rand[seed]["gamma1"][-100:].mean())
    gammas2_rand.append(ress_rand[seed]["gamma2"][-100:].mean())
    betas.append(ress[seed]["beta"].iloc[-1])
    betas_rand.append(ress_rand[seed]["beta"].iloc[-1])
gammas1 = np.array(gammas1)
gammas2 = np.array(gammas2)
gammas1_rand = np.array(gammas1_rand)
gammas2_rand = np.array(gammas2_rand)

In [4]:
import numpy as np
loss=[]
loss_rand=[]
for seed in range(1,nun_seed):
    loss.append(ress[seed]["loss"][-10:].mean())
    loss_rand.append(ress_rand[seed]["loss"][-10:].mean())
loss = np.array(loss)
loss_rand = np.array(loss_rand)

In [5]:
resss = pd.DataFrame({"loss":loss, "loss_rand":loss_rand, "beta": betas, "beta_rand":betas_rand})
resss["diff_loss"] = loss - loss_rand
resss

loss    loss_rand  beta  beta_rand  diff_loss
0  6120.571973  6043.725391   1.0        1.0  76.846582
1  6416.991650  6507.025293   1.0        1.0 -90.033643
2  7629.834082  7642.962598   1.0        1.0 -13.128516
3  9844.549707  9850.500293   1.0        1.0  -5.950586
4  9180.923535  9172.978809   1.0        1.0   7.944727
5  6649.740869  6668.946631   1.0        1.0 -19.205762
6  8682.861816  8695.245801   1.0        1.0 -12.383984
7  9232.149316  9234.696875   1.0        1.0  -2.547559
8  9569.857031  9573.175098   1.0        1.0  -3.318066

In [6]:
resss["diff_loss"].mean(), resss["diff_loss"].std()/np.sqrt(10)

(-6.864089626736233, 13.41548660851857)

In [7]:
resss["diff_loss"].std()/np.sqrt(10)

13.41548660851857

In [8]:
gammas1_rand.mean(), gammas2_rand.mean()

(9.71600125138721e-05, 7.954033935674908e-05)

In [9]:
gammas1.mean(), gammas2.mean()

(0.0001745974198759222, 4.7118497807079824e-05)

In [21]:
gammas1

array([0.00013464, 0.00014642, 0.00021675, 0.00013684, 0.00015093,
       0.00026247, 0.00016712, 0.00020144, 0.00015476])

In [22]:
gammas1_rand.std(), gammas2_rand.std()

(4.8131386600095006e-05, 2.5925434575284002e-05)

In [23]:
loss, loss_rand

(array([6120.57197266, 6416.99165039, 7629.83408203, 9844.54970703,
        9180.92353516, 6649.74086914, 8682.86181641, 9232.14931641,
        9569.85703125]),
 array([6043.72539062, 6507.02529297, 7642.96259766, 9850.50029297,
        9172.97880859, 6668.94663086, 8695.24580078, 9234.696875  ,
        9573.17509766]))

In [24]:
loss.mean(), loss_rand.mean()

(8147.497775607639, 8154.361865234374)

In [12]:
(loss/loss_rand).mean()

0.999166271014589

In [25]:
resss = pd.DataFrame({"loss":loss, "loss_rand":loss_rand, "beta": betas, "beta_rand":betas_rand})
resss

loss    loss_rand  beta  beta_rand
0  6120.571973  6043.725391   1.0        1.0
1  6416.991650  6507.025293   1.0        1.0
2  7629.834082  7642.962598   1.0        1.0
3  9844.549707  9850.500293   1.0        1.0
4  9180.923535  9172.978809   1.0        1.0
5  6649.740869  6668.946631   1.0        1.0
6  8682.861816  8695.245801   1.0        1.0
7  9232.149316  9234.696875   1.0        1.0
8  9569.857031  9573.175098   1.0        1.0

In [96]:
res["gamma1"][0:].rolling(100).mean().plot()

<AxesSubplot:>